RebootYourJavaScript/demos/5 - ie9ify/after/PhotoGallery/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.WebPages;
using PhotoGallery.Repositories;
using WebMatrix.WebData;
using System.Web.Helpers;

namespace PhotoGallery.Controllers
{
    public class GalleryController : Controller
    {
        public ActionResult Default()
        {
            ViewBag.Title = "Photo Gallery";

            var db = new PhotoGalleryRepository();
            var galleries = db.GetGalleryList();

            return View(galleries);
        }

        public ActionResult List()
        {
            var db = new PhotoGalleryRepository();
            var galleries = db.GetGalleryList();

            var jsonGalleries = galleries.Select(gallery => new jsonGallery
                                                                {
                                                                    id = gallery.Id, name = gallery.Name
                                                                }).ToList();

            return Json(jsonGalleries, JsonRequestBehavior.AllowGet);
        }
        
        [Authorize]
        public ActionResult New()
        {
            ViewBag.Title = "New Gallery";

            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult New(string Name)
        {
            if (Name.IsEmpty()) 
                ModelState.AddModelError("Name", "You must specify a gallery name.");
            
            if (ModelState.IsValid)
            {
                var db = new PhotoGalleryRepository();
                var nameExists = db.GetGalleryCount(Name) > 0;
                
                if (nameExists)
                {
                    ModelState.AddModelError("Name", "A gallery with the supplied name already exists.");
                }
                else
                {
                    int galleryId = db.CreateGallery(Name);
                    return RedirectToAction("View", new { id = galleryId });
                }
            }

            return View();
        }

        [OutputCache(Duration = 60)]
        public ActionResult Thumbnail(int id)
        {
            var db = new PhotoGalleryRepository();

            var gallery = db.GetGallery(id);
            if (gallery == null)
            {
                return HttpNotFound();
            }

            var photos = db.GetTopPhotosForGallery(id);
            if (photos.Count == 0)
            {
                return File(Server.MapPath("~/Content/Images/gallery-empty.png"), "image/jpeg");
            }

            using (var generator = new MultiThumbnailGenerator())
            {
                foreach (var photo in photos)
                {
                    using (var imageStream = new MemoryStream(photo.FileContents))
                    {
                        using (var image = System.Drawing.Image.FromStream(imageStream))
                        {
                            generator.AddImage(image);
                        }
                    }
                }
                using (var outStream = new MemoryStream())
                {
                    generator.WritePngToStream(outStream);
                    var image = new WebImage(outStream);
                    image.Write();
                    
                    return null;
                }
            }
        }

        public ActionResult View(int id)
        {
            var db = new PhotoGalleryRepository();

            var gallery = db.GetGallery(id);
            if (gallery == null)
                return HttpNotFound();

            var photos = db.GetPhotosForGallery(id);

            ViewBag.Title = "Gallery - " + gallery.Name;
            ViewBag.Name = gallery.Name;
            ViewBag.GalleryId = id;

            return View(photos);
        }

        public ActionResult Upload(int id)
        {
            WebSecurity.RequireAuthenticatedUser();

            var db = new PhotoGalleryRepository();
            var gallery = db.GetGallery(id);

            if (gallery == null)
                return HttpNotFound();

            ViewBag.Title = "Upload Photo to Gallery - " + gallery.Name;
            
            return View(gallery);
        }

        [HttpPost]
        public ActionResult Upload()
        {
            var db = new PhotoGalleryRepository();

            int id = Request.Url.Segments[3].AsInt();
            var numFiles = Request.Files.Count;
            int imageId = 0;
            
            for (int i = 0; i < numFiles; i++)
            {
                var file = Request.Files[i];
                if (file.ContentLength > 0)
                {
                    var fileUpload = new WebImage(file.InputStream);
                    var fileTitle = Path.GetFileNameWithoutExtension(file.FileName).Trim();
                    if (fileTitle.IsEmpty())
                    {
                        fileTitle = "Untitled";
                    }
                    var fileExtension = Path.GetExtension(file.FileName).Trim();
                    var fileBytes = fileUpload.GetBytes();

                    imageId = db.InsertImage(id, WebSecurity.CurrentUserId, fileTitle, 
                        fileExtension, fileUpload.ImageFormat, fileBytes.Length, fileBytes);
                }
            }

            return RedirectToAction("View", "Photo", new { id = imageId });
        }
    }

    public class jsonGallery
    {
        public int id { get; set; }
        public string name { get; set; }
    }
}

RebootYourJavaScript/demos/5 - ie9ify/after/PhotoGallery/Controllers/TagController.cs
using System.Web.Mvc;
using PhotoGallery.Repositories;
using System.Dynamic;
using System.Web.Helpers;

namespace PhotoGallery.Controllers
{
    public class TagController : Controller
    {
        public ActionResult Default()
        {
            ViewBag.Title = "View All Tags";

            var repository = new TagRepository();
            var tagsList = repository.GetTagList();

            return View(tagsList);
        }

        [OutputCache(Duration = 60)]
        public ActionResult Thumbnail(string id)
        {
            var repository = new TagRepository();
            var tag = repository.GetTag(id);
            var photoList = repository.GetPhotoList(id);

            if (tag != null && photoList.Count > 0)
            {
                using (MultiThumbnailGenerator generator = new MultiThumbnailGenerator())
                {
                    foreach (var photo in photoList)
                    {
                        using (var imageStream = new System.IO.MemoryStream(photo.FileContents))
                        {
                            using (var image = System.Drawing.Image.FromStream(imageStream))
                            {
                                generator.AddImage(image);
                            }
                        }
                    }

                    using (var outStream = new System.IO.MemoryStream())
                    {
                        generator.WritePngToStream(outStream);
                        var image = new WebImage(outStream);
                        image.Write();
                    }
                }

                return null;
            }
            
            return Redirect("~/Content/Images/gallery-empty.png");
        }

        public ActionResult Get(string id)
        {
            ViewBag.Title = "View Tag - " + id;

            dynamic model = new ExpandoObject();
            model.TagName = id;

            var repository = new TagRepository();
            model.Photos = repository.GetPhotos(id);
            model.SimilarTags = repository.GetSimilarTags(id);
            
            return View("View", model);
        }
    }
}

RebootYourJavaScript/demos/5 - ie9ify/after/PhotoGallery/Controllers/UserController.cs
using System.Web.Mvc;
using System.Dynamic;
using System.Web.WebPages;
using PhotoGallery.Repositories;
using WebMatrix.WebData;

namespace PhotoGallery.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public ActionResult Default()
        {
            var userRepository = new UserRepository();
            var user = userRepository.GetUserById(WebSecurity.CurrentUserId);

            ViewBag.Title = "Edit Profile - " + user.DisplayName;

            return View(user);
        }
        
        [HttpPost]
        public ActionResult Default(string displayName, string bio)
        {
            if (displayName.IsEmpty()) 
                ModelState.AddModelError("displayName", "You must specify a display name.");

            if (ModelState.IsValid)
            {
                var userRepository = new UserRepository();
                userRepository.UpdateUserProfile(displayName, bio, WebSecurity.CurrentUserId);
                
                return RedirectToAction("View", new { id = WebSecurity.CurrentUserId}); 
            }

            return View();
        }

        public ActionResult View(int id)
        {
            dynamic userModel = new ExpandoObject();

            var userRepository = new UserRepository();
            var user = userRepository.GetUserById(id);

            if (user == null)
            {
                return HttpNotFound();
            }

            ViewBag.Title = "User - " + user.DisplayName;

            var photo = userRepository.GetPhotos(id);

            userModel.User = user;
            userModel.Photos = photo;

            return View(userModel);
        }
    }
}

RebootYourJavaScript/demos/5 - ie9ify/after/PhotoGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title> 
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" />
        <link href="@Url.Content("~/favicon.ico")" rel="shortcut icon" type="image/x-icon" />
        <script src="@Url.Content("~/Scripts/jquery-1.5.2.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery.ie9ify.js")" type="text/javascript"></script>
        <script type="text/javascript">
            $(function () {
                $('head').ie9ify({
                    navColor: 'Yellow',
                    tasks: [
                        {
                            'name': 'Galleries',
                            'action': '/Gallery',
                            'icon': '/Content/Images/icon-gallery.ico'
                        },
                        {
                            'name': 'Tags',
                            'action': '/Tag',
                            'icon': '/Content/Images/icon-tags.ico'
                        },
                        {
                            'name': 'Account',
                            'action': '/User',
                            'icon': '/Content/Images/icon-account.ico'
                        }
                    ]
                });
                
                $('#site-logo').ie9ify('enablePinning');

                $('#header').ie9ify('pinTeaser', {
                    addStartLink: false
                });

                if ($.ie9ify.isPinned()) {
                    $.getJSON('Gallery/List', function (data) {
                        var itemList = [];

                        $.each(data, function (key, val) {
                            var item = {
                                'name': data[key].name,
                                'url': 'Gallery/View/' + data[key].id,
                                'icon': '/Content/Images/icon-gallery.ico'
                            };

                            itemList.push(item);
                        });

                        $.ie9ify.addJumpList({
                            title: 'Photo Galleries',
                            items: itemList
                        });
                    });

                    $.ie9ify.createThumbbarButtons({
                        buttons: [{
                            icon: '/Content/Images/download.ico',
                            name: 'Download Images',
                            click: function () {
                                document.location = 'Gallery';
                            }
                        },
                        {
                            icon: '/Content/Images/icon-tags.ico',
                            name: 'Tag Images',
                            click: function () {
                                document.location = 'Tag';
                            }
                        }]
                    });

                    setInterval(function () {
                        $.getJSON('Photo/CommentsForUser/' + new Date().getTime() , function (data) {
                            $.ie9ify.clearOverlay();

                            var itemList = [];
                            var commentCount = parseInt($('#commentCount').val());

                            if (data.length > commentCount) {
                                $.ie9ify.flashTaskbar();
                                $('#commentCount').val(data.length);

                                $.ie9ify.addOverlay({
                                    title: 'New comment: ' + data[0].text + ' (' + data[0].date + ')',
                                    icon: '/Content/Images/comment.ico'
                                });
                            }
                        });
                   }, 5000);
                }
            });
        </script>
    </head>
    <body>
    <div id="header"></div>
    <div id="banner">
            <p class="site-title">
                <img alt="Photo Gallery Site Logo" id="site-logo" src="@Url.Content("~/Content/Images/galleryIcon.ico")" width="32" height="32" />
                <a href="@Url.Action("Default", "Gallery")">Photo Gallery</a>
            </p>
            <ul id="menu">
                <li class="galleries"><a href="@Url.Action("Default", "Gallery")">Galleries</a></li>
                <li class="tags"><a href="@Url.Action("Default", "Tag")">Tags</a></li>
                <li class="account"><a href="@Url.Action("Default", "User")">Account</a></li>
                <li class="login">
                    @if (WebSecurity.IsAuthenticated)
                    {
                        <text>Welcome <strong>@WebSecurity.CurrentUserName</strong>!
                        <a href="@Url.Action("Logout", "Account")">Logout</a></text>
                    }
                    else
                    {
                        <text><a href="@Url.Action("Login", "Account")">Login</a></text>
                    }
                </li>
            </ul>
        </div>        
        <div id="page">
            @RenderBody()
        </div>
        <div id="footer">
            &copy; @DateTime.Now.Year - Photo Gallery 
        </div>
        <input type="hidden" id="commentCount" value="0" />
    </body>
</html>